version: "3.8"

#todo : kafka, opensearch, reids, ...

services:
  eureka:
    build: ./eureka
    image: eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - msa-network

  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge


