version: "3.8"

services:
  eureka:
    build: ./eureka
    image: eureka:latest
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - msa-network

networks:
  msa-network:
    driver: bridge


